language: objective-c
os: osx
cache: cocoapods
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
  - RFCI_PRODUCT_NAME="RFInitializing"
jobs:
  include:
    - osx_image: xcode11
      env: RFCI_TASK="POD_LINT"
script:         ./.travis.sh MAIN
